import { createClient } from '@supabase/supabase-js';
import path from 'path';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const envPath = path.resolve(__dirname, '../.env.local');

dotenv.config({ path: envPath });

const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
);

/**
 * Specifically seeds the expanded narrative paragraphs into Level 7
 */
async function seedLevel7Narrative() {
    console.log("🚀 Starting specialized seeding for Level 7 Narrative...");

    const targetLevelId = 7;

    // LEAVING ARRAY AS IS FOR MANUAL ENTRY
    const paragraphs = [
        "Abnormally high tides washed aboard the vessel about noon above the bay abroad where he stood absently, absolutely and abundantly clear, accidentally occurring accordingly.",
        "Accurately aimed and accusingly pointed across the room, actually helping additionally and adequately prepared, she looked adoringly at the ship adrift, adroitly maneuvering adversely.",
        "Afar in the distance, afield and afoot, the wood stayed afloat while afoot once more, starting afresh after the event, afterward and afterwards, beginning again.",
        "Against the grain ago, ships ran aground ahead of others alike, where all allegedly and alluringly failed, almost reaching the flag aloft.",
        "Alone along the path alongside the shore, he spoke aloud alphabetically, having already and also altogether finished, as he always and amazingly did.",
        "Amiss in the plan amply rewarded, they watched amusedly and analogously, thinking analytically while others reacted angrily, annually, anonymously, anxiously, or in any way.",
        "Anyway, anyways, or anywhere, they lived apart, apiece, apologetically and apparently fine, appreciatively and appropriately dressed, being approximately on time.",
        "Aptly described and arbitrarily chosen, he spoke archly and ardently around the room, aright at last, aristocratically, artfully, articulately, and artificially posed.",
        "Artlessly done, he stepped aside while asleep, aspiringly and assuredly moving, astonishingly going astray and asunder at the point athwart the deck.",
        "Atop the hill attentively watched, audibly and austerely quiet, he acted authentically and automatically, avidly and avowedly moving away, feeling awfully strange.",
        "Awkwardly moving awry, he stepped back and backwards badly, barely and basically safe, beautifully placed behind the line below.",
        "Beneath the surface besides the best and better options between them, beyond the reach biannually, biweekly, bitterly, and bleakly cold.",
        "Blindly following blissfully unaware, he bloodily and boastfully fought boldly, briefly and brightly shining brilliantly, moving briskly and broadly.",
        "Brotherly and brusquely, he brutally and buoyantly worked busily by the desk, calmly and candidly speaking cannily and capably.",
        "Carefully and carelessly, casually or catastrophically, they moved cautiously and ceaselessly centrally, certainly and cheaply buying what was cheerfully sold.",
        "Chemically altered and chiefly responsible, childishly and chronologically ordered, he acted civilly, cleanly, and clear, clearly and cleverly turning clockwise.",
        "Closely and coarsely, coldly and collectively, they spoke colloquially and combatively, living comfortably, comically, commercially, and commonly.",
        "Compactly and comparatively, compassionately and compatibly, he worked competently, competitively, complacently, completely, complexly, and composedly.",
        "Comprehensively and compulsively, compulsorily and computationally, he worked conceivably, conceptually, concisely, conclusively, concretely, and concurrently.",
        "Conditionally and confidently, confidentially and confirmingly, they spoke conflictingly, conformably, confusedly, congenially, congratulatorily, and connectedly.",
        "Conscientiously and consciously, consecutively and consequently, he lived conservatively, considerably, considerately, consistently, consolingly, and conspicuously.",
        "Constantly and constitutionally, constrainedly and constructively, consumersly and contagiously, they lived contemporaneously, contemptuously, contentedly, and contextually.",
        "Continually and continuously, contractually and contradictorily, contrarily and contrastingly, they acted contritely, controversially, conveniently, and conventionally.",
        "Conversationaly and conversely, convincingly and coolly, they worked cooperatively, copiously, cordially, correctively, correctly, and correspondingly.",
        "Corruptly and costly, counter and counterintuitively, they fought courageously, courteously, covertly, cowardly, cozily, and craftily.",
        "Crazily and creatively, credibly and credulously, they lived criminally, critically, crookedly, crossly, crucially, and crudely.",
        "Cruelly and crushingly, cryptically and culturally, they worked cunningly, curiously, currently, cursedly, cursorily, and curtly.",
        "Cynically and daily, daintily and damnably, it felt damply, dangerously, daringly, darkly, dashly, and dazedly.",
        "Dearly and deathly, debatably and decisively, he felt deep and deeply, defensivelly, deferentially, defiantly, and definitely.",
        "Deftly and dejectedly, deliberately and delicately, they ate deliciously and delightedly, deliriously, democratically, demonically, and demonstrably.",
        "Demurely and denselly, departmentally and dependably, they acted deplorably, depressingly, derisively, deservedly, designatedly, and desirably.",
        "Despairingly and desperately, despicably and despitefully, they lived despondently, destructively, detachedly, detailedly, determinedly, and detrimentally.",
        "Deviantly and devotedly, devoutly and dexterously, they moved diabolically, diagonally, diametrically, dictatorially, differentially, and differently.",
        "Diffidently and digitally, dignifiedly and diligently, they saw dimly and diplomatically, direct and directly, disadvantageously, and disastrously.",
        "Disbelievingly and discernibly, disciplinarily and disconnectedly, they lived discontentedly, discontinuously, discordantly, discouragingly, discourteously, and discursively.",
        "Disdainfully and disgracefully, disguisedly and dishonestly, they acted dishonourably, disingenuously, disinterestedly, disjointedly, dismally, and dismayedly.",
        "Disobediently and disorderly, disorganizedly and disparagingly, they lived dispassionately, dispellingly, dispensably, dispersedly, dispiritedly, and displeasedly.",
        "Disproportionately and disputatiously, disquietingly and disregardedly, they lived disreputably, disrespectfully, disruptively, dissatisfiedly, dissemblingly, and disseminatedly.",
        "Distant and distantly, distinctively and distinctly, they moved distinguishably, distortedly, distractedly, distractingly, distraughtly, and distressingly.",
        "Distributively and distrustfully, disturbingly and divergently, they lived diversely, divinely, divisively, docilely, doggedly, and dogmatically.",
        "Domestically and dominantly, doomedly and dormantly, they lived doubtingly, doubtless, down, downhill, downstairs, and downstream.",
        "Downwards and drably, drastically and dreadfully, they moved dreamily, drearily, drinkably, drowsily, drunkenly, and dryly.",
        "Dubiously and duly, dumbly and dutifully, they worked dynamically, eagerly, earlier and early, earnestly, and earthly.",
        "Easily moving east, eastward and eastwards, they heard echoingly, ecologically, economically, ecstatically, edgeways, and editorially.",
        "Educationally and eerily, effectively and effectually, they worked efficiently, effortlessly, effusively, egregiously, elaborately, and elatedly.",
        "Electrically and electronically, elegantly and elementally, they worked elementarily, eligibly, eloquently, elsewhere, emphatically, and empirically.",
        "Emulously and enchantingly, encouragingly and endlessly, they worked enduringly, energetically, enigmatically, enjoyably, enormously, and enough.",
        "Enquiringly and enragedly, entertainingly and enthralledly, they acted enthusiastically, entirely, enviously, environmentally, equally, and equitably.",
        "Equivalently and equivocally, erratically and erroneously, they lived erstwhile, especial, especially, essentially, eternally, and ethically.",
        "Ethnically and euphorically, evasively and even, they lived evenly, eventually, ever, evermore, everywhere, and evidently.",
        "Evocatively and exact, exactly and exaggeratedly, they worked excellently, exceptionably, exceptionally, excessively, exclusively, and excruciatingly.",
        "Excusably and executively, exemplarily and exhaustively, they worked exhilaratingly, exorbitantly, exotically, expansively, expectantly, and expediently.",
        "Expeditiously and expensively, experimentally and expertly, they worked explicitly, explosively, exponentially, expressly, exquisitely, and extensively.",
        "Externally and extortionately, extra and extractively, they worked extraordinarily, extravagantly, extremely, exuberantly, exultantly, and eye-catchingly.",
        "Fabulously and facially, factually and faintly, they lived fairly, faithfully, faltersly, familiarly, famously, and fanatically.",
        "Fancifully and fantastically, moving far, farther, and farthest, they lived fascinatingly, fashionably, fast, fatalistically, and fatally.",
        "Fatly and favorably, fearfully and fearlessly, they lived feasibly, federally, feebly, felicitously, ferociously, and ferrily.",
        "Fervently and festively, feudally and fiercely, they lived fiery, fifthly, figuratively, filthily, finally, and financially.",
        "Finely and finitely, firmly and first, they lived firstly, fitfully, fittingly, fixedly, flabbily, and flaccidly.",
        "Flagrantly and flamboyantly, flashily and flatly, they lived flawlessly, fleetly, flexibly, flightily, flimsily, and flippantly.",
        "Flirtatiously and florally, floridly and fluently, they lived fluidly, flush, foamily, focally, fondly, and foolishly.",
        "Forbearingly and forbiddingly, forcefully and forcibly, they stood fore, foremost, forever, forgetfully, forgivingly, and formally.",
        "Formerly and formidably, formlessly and forth, they lived forthcomingly, forthwith, fortuitously, fortunate, fortunately, and forward.",
        "Forwards and foully, fourthly and fractionally, they lived fragilely, fragerantly, frankly, frantically, fraternally, and fraudulently.",
        "Freely and French, frenetically and frenziedly, they acted frequent, frequently, freshly, fretfully, friendly, and frightenedly.",
        "Frighteningly and frigidly, friskily and frivolously, they lived front, frontally, frontward, frontwards, frostily, and frothily.",
        "Frowningly and frugally, fruitfully and fruitlessly, they lived frustratedly, fully, fulsomely, functionally, fundamentally, and funnily.",
        "Furiously and further, furthermore and furthest, they lived furtively, fussily, futilely, gaily, gainfully, and gallantly.",
        "Gamely and garishly, gastronomically and gaudily, they lived gazingly, generally, generously, genetically, genially, and gently.",
        "Genuinely and geographically, geologically and geometrically, they lived giddily, gingerly, glaringly, gleefully, glibly, and glidingly.",
        "Glimmeringly and gloatingly, globally and gloomily, they lived gloriously, glossily, glowingly, gluttonously, goldly, and good.",
        "Gorgeously and govermentally, gracefully and graciously, they lived gradually, grammatically, grandly, graphically, gratefully, and gratuitously.",
        "Gratifiedly and gravely, greedily and gregariously, they lived greyminly, grievously, grimly, grossly, grotesquely, and groundedly.",
        "Grovellingly and grudgingly, gruffly and grumblingly, they lived grumpily, guiltily, gullibly, gushingly, habitually, and haggardly.",
        "Haltingly and handily, haplessly and haphazardly, they lived haply, happily, harassedly, hard, hardly, and harmlessly.",
        "Harmoniously and harshly, hastily and hatefully, they lived haughtily, hauntingly, hazardously, hazily, headily, and headlong.",
        "Healthily and heartily, heartlessly and heatedly, they lived heavenward, heavily, hectically, heedlessly, hefty, and heinously.",
        "Hellishly and helpfully, helplessly and heraldically, they lived here, hereabouts, hereafter, hereby, herein, and hereof.",
        "Hereto and heretofore, herewith and heroically, they lived hesitantly, hideously, high, highly, hilariously, and hindward.",
        "Hissingly and historically, hitherto and hoarsely, they lived hollowly, holistically, hollowly, holy, homeward, and homewards.",
        "Honestly and honeyed, honorably and hopefully, they lived hopelessly, horizontally, horribly, horridly, horrificly, and horrifyingly.",
        "Hospitably and hostilely, hotly and hourly, they lived houseward, how, however, howsoever, hugely, and humanely.",
        "Humanly and humbly, humidly and humiliatingly, they lived humorously, hungrily, hurriedly, hurtfully, hushingly, and hydraulically.",
        "Ideally and identically, idiomatically and idiotically, they lived idly, ignobly, ignorantly, ill, illegally, and illegibly.",
        "Illegitimately and illogically, illustratively and illustriously, they lived imaginatively, immaculately, immaterially, immaturely, immeasurably, and immediately.",
        "Immensely and imminently, immoderately and immodestly, they lived immorally, immortally, immovably, immunely, immutably, and impalpably.",
        "Impartially and impassively, impatiently and impeccably, they lived impenetrably, imperatively, imperceptibly, imperfectly, imperially, and imperiously.",
        "Impermissibly and impersonally, impertinently and impetuously, they lived impiously, implacably, implausibly, implicitly, impolitely, and importantly.",
        "Importunately and imposingly, impossibly and impotently, they lived impracticably, imprecisely, impregnably, impressively, improbably, and imprudently.",
        "Impudently and impulsively, impurely and inaccessibly, they lived inaccurately, inadequately, inadmissibly, inadvertently, inadvisably, and inalienably.",
        "Inane, inanely, inappropriately and inarticulately, they lived inattentively, inaudibly, inaugurally, inauspiciously, incalculably, and incandescently.",
        "Incapably and incautiously, incendiarily and incensedly, they lived incentively, incessantly, incidental, incidentally, incipiently, and incisively.",
        "Incoherently and incomparably, incompatibly and incompetently, they lived incompletely, inconceivably, inclusivelly, inconclusively, incongruously, and inconsequentially.",
        "Inconsiderately and inconsistently, inconspicuously and incontestably, they lived incontinently, incontrovertibly, inconveniently, incorrectly, incorrigibly, and incorruptibly.",
        "Increasingly and Incredibly, incredulously and incriminatory, they lived incurably, indecisively, indecorously, indeed, indefatigably, and indefinitely.",
        "Indelibly and independently, indescribably and indeterminately, they lived indicatively, indifferently, indigenously, indignantly, indirectly, and indiscreetly.",
        "Indispensably and indisputably, indistinctly and indistinguishably, they lived individually, indolently, indubitably, indulgently, industrially, and industriously.",
        "Ineffably and ineffectively, ineffectually and inefficiently, they lived inelegantly, ineluctably, ineptly, inequitably, ineradicably, and inertly.",
        "Inescapably and inestimably, inevitably and inexact, they lived inexactly, inexcusably, inexhaustibly, inexorably, inexpensively, and inexpertly.",
        "Inexplicably and inexpressibly, inextricably and infallibly, they lived infamously, infectiously, inferiorly, infernally, infinitely, and infinitesimally.",
        "Inflamedly and inflationarily, inflexibly and influentially, they lived informally, informationally, informatively, infrequently, infuriatingly, and ingeniously.",
        "Ingenuously and ingratiatingly, inherent, inherently and inheritedly, they lived inhumanly, inhospitably, inimitably, iniquitously, and initially.",
        "Injectively and injudiciously, injuredly, injuringly and injurious, they lived inland, innately, inner, innermost, and innocently.",
        "Innocuously and innovatively, inoffensively, inordinately and inorganically, they lived inquiringly, inquisitively, insanely, insatiably, and inscribedly.",
        "Insecurely, insensibly, insensitively, inseparably and inside, they lived insidiously, insightfully, insignificantly, insincerely, and insinuatingly.",
        "Insipidly, insistently, insolently, insolubly and inspirationally, they lived instantly, instantaneously, instead, instinctively, and institutionally.",
        "Instructively, instrumentally, insufferably, insufficiently and insultingly, they lived insuperably, intactly, intangibly, integrally, and intellectually.",
        "Intelligently, intelligibly, intemperately, intendedly and intensely, they lived intensifiedly, intensively, intentionally, interactively, and intercedingly.",
        "Interchangeably, interdepartmentally, interdependently, interestingly and intermittently, they lived internally, internationally, interpersonally, interpretively, and interrogatively.",
        "Interruptingly, intersectingly, interspersedly, interstingly and intertwinedly, they lived interveningly, intimately, intimidatingly, intolerably, and intolerants.",
        "Intoxicatedly, intractably, intramuscularly, intransigently and intrepidly, they lived intricately, intriguingly, intrinsically, introvertedly, and intrusively.",
        "Intuitively, invaluably, invariably, invasively and inversely, they lived invertedly, investigatively, invidiously, invigoratingly, and invincibly.",
        "Invisibly, involuntarily, inwardly, inwardly and inwards, they lived inworking, iatedly, ironically, irrationally, and irregularly.",
        "Irrelevant, irrelevantly, irreparably, irreplaceably and irrepressibly, they lived irresistibly, irresolutely, irrespectively, irresponsibly, and irretrievably.",
        "Irreverently, irreversibly, irritably, irritatingly and isolationally, they lived isometrically, isothermally, Italian, itemizedly, and itinerantly.",
        "Jaggedly, jarringly, jauntily, jazzily and jealously, they lived jeeringly, jejunely, jerkily, jestingly, and jocularly.",
        "Jointly, jokingly, jollily, jovially and joyfully, they lived joylessly, jubilantly, judicially, judiciously, and juicily.",
        "Jumbledly, jumpily, just, justifiably and justly, they lived keenly, kid-likely, kind-heartedly, kindly, and kinematically.",
        "Kinetically, kingly, knavishly, kneeling and knightly, they lived knittingly, knotty, knowingly, knowledgeably, and laboriously.",
        "Lackadaisically, laconically, laggingly, lamentably and languidly, they lived languishingly, largely, lasciviously, last, and lastly.",
        "Late, lately, latently, later and laterally, they lived latest, laudably, laughably, lavishly, and lawfully.",
        "Lawlessly, laxly, lazily, leanly and learnedly, they lived least, left, leftward, leftwards, and legally.",
        "Legibly, legislatively, legitimately, leisurely and lengthily, they lived leniently, less, lesser, lest, and lethally.",
        "Levelly, lewdly, lexically, liably and liberally, they lived libertarianly, licentiously, lickingly, lie-abed, and lifelessly.",
        "Lightly, like, likely, likewise and limitedly, they lived limitlessly, limpidly, limpingly, linearly, and lingeringly.",
        "Linguistically, liquially, lisperingly, listlessly and literally, they lived literarily, little, live, lively, and livingly.",
        "Loathingly, locally, logically, logistically and lonesomely, they lived long, longingly, longitudinally, long-term, and longways.",
        "Loosely, lopsidedly, loud, loudly and lovably, they lived lovingly, low, lower, lowly, and loyally.",
        "Lucidly, luckily, lucratively, ludicrously and lugubriously, they lived lullingly, luminously, lumpishly, lurchingly, and luringly.",
        "Luridly, lusciously, lustfully, lustily and luxuriantly, they lived luxuriously, lyingly, lyrically, macabrely, and machinally.",
        "Madly, magically, magisterially, magnanimously and magnetically, they lived magnificently, magnifiedly, mainly, majesticly, and majorly.",
        "Maladroitly, malcontentedly, maliciously, malignantly and malleably, they lived manageably, managerially, mandatorily, maneuverably, and mangily.",
        "Manfully, mangledly, maniacally, manifestly and manipulatively, they lived manly, mannerly, manually, manufacturally, and many.",
        "Marginally, maritally, markedly, marketably and martially, they lived marvelously, masculinely, masochistically, massively, and masterfully.",
        "Materially, matematically, matrilineally, maturely and maudlinly, they lived maximally, maybe, meagerly, meanderingly, and meaningfully.",
        "Meanly, meantime, meanwhile, measurably and mechanically, they lived medially, mediately, medically, medicinally, and meditatively.",
        "Meekly, melodramatically, memorablely, menacingly and mendaciously, they lived mentally, mercenarily, mercifully, merely, and meritocratically.",
        "Merrily, messily, metaphorically, metaphysically and methodically, they lived meticulously, metonymically, metrically, microscopicly, and midly.",
        "Midships, midway, mightily, mildly and militarily, they lived milkily, millennially, mimically, mindfully, and mindlessly.",
        "Minimally, ministerially, minutely, miraculously and mirthfully, they lived misanthropically, mischievously, miserably, misguidingly, and misleadingly.",
        "Mistakenly, mistily, mockingly, moderately and modernly, they lived modestly, modishly, moistly, molecularly, and momentarily.",
        "Momentously, monastically, monetarily, monolithically and monotonously, they lived monthly, moodily, moonily, morally, and morbidly.",
        "Moreover, morosely, morphologically, mortally and mostly, they lived motherly, motionlessly, motivationally, mournfully, and movingly.",
        "Muddily, muddy, multifariously, multilaterally and multilingually, they lived multiply, mundanely, municipally, munificently, and murderously.",
        "Murmuringly, musically, musingly, mutably and mutedly, they lived mutually, mysteriously, mystically, mythically, and naively.",
        "Nakedly, namely, narcissistically, narrowly and nasally, they lived nastily, nationally, natively, naturally, and naughtily.",
        "Nauseatingly, near, nearby, nearly and neatly, they lived nebulously, necessarily, needlessly, needingly, and nefariously.",
        "Negatively, neglectfully, negligently, negligibly and negotiably, they lived neighbourly, neoclassically, nervously, neurotically, and neutrally.",
        "Never, nevertheless, newly, next and nicely, they lived niggardly, nightly, nimbly, nobly, and nocturnally.",
        "Noisily, nominally, nonchalantly, noncommittally and non-conflictingly, they lived nonsensically, normally, north, northward, and northwards.",
        "Notably, notedly, nothing, noticeably and notoriously, they lived notwithstanding, novelistically, now, nowadays, and nowhere.",
        "Noxiously, numbly, numerically, nuptially and nutritiously, they lived obdurately, obediently, obesely, objectionably, and objectively.",
        "Obligatorily, obliquely, obliviously, obnoxiously and obscenely, they lived obscurely, obsequiously, observably, observantly, and obsessively.",
        "Obsoletely, obstinately, obstructively, obtrusively and obtusely, they lived obviously, occasionally, occupationally, odiously, and off.",
        "Offensively, offerings, offhand, office and officially, they lived officiously, offside, offstage, offward, and often.",
        "Ogreishly, oily, okay, oldenly and ominously, they lived omissionly, omnipotently, omnipresently, omnisciently, and on.",
        "Once, one-sidedly, onerously, on-line and only, they lived onward, onwards, opaquely, openly, and operationally.",
        "Operatively, opinionatedly, opportunely, oppressively and optically, they lived optimally, optimistically, optionally, orally, and oracularly.",
        "Orally, oratorically, orbitally, ordinarily and organizationally, they lived organically, originally, ornamentally, ornately, and orthodoxly.",
        "Ostensibly, ostentatiously, other, otherwise and other-worldly, they lived out, outbound, outlandishly, out-of-doors, and outrageously.",
        "Outright, outside, outspokenly, outward and outwardly, they lived outwards, over, overboard, overconfidently, and overhand.",
        "Overhead, overland, overnight, overly and overpoweringly, they lived overseas, overtime, overwhelmingly, overwise, and overwroughtly.",
        "Overtly, owlishly, painfully, painstakingly and palatably, they lived palely, pallidly, palpably, palpitatingly, and panickily.",
        "Paradoxically, parallely, paralyzingly, paramountly and paranoidly, they lived parasitically, pardonably, parentally, parenthetically, and parochially.",
        "Partially, particularly, partisanly, partitioningly and partly, they lived passionately, passively, past, pastorally, and patently.",
        "Paternally, pathetically, pathologically, patiently and patriotically, they lived patteringly, patronizingly, peaceably, peacefully, and peculiarly.",
        "Pedagogically, pedantically, pedestrianly, peerlessly and peevishly, they lived penally, penetratingly, penitently, pensively, and penuriously.",
        "Pepidly, peradventure, perceptibly, perceptively and perchance, they lived percussively, peremptorily, perennially, perfectly, and perfidiously.",
        "Perfunctorily, perhaps, perilously, periodically and peripherally, they lived perishably, perjuriously, permanently, permissibly, and permissively.",
        "Perniciously, perpendicularly, perpetually, perplexedly and persistently, they lived personably, personally, perspicaciously, perspicuously, and persuasively.",
        "Pertinently, perturbedly, pervasively, perversely and pessimistically, they lived petulantly, phantomly, phenomenally, philanthropically, and philologically.",
        "Philosophically, phlegmatically, phonetically, photogenically and photographically, they lived phrasally, physically, physiologically, pianistically, and pickily.",
        "Pictorially, picturesquely, piercingly, piecemeal and piercingly, they lived piously, piquantly, piratically, pitifully, and pitilessly.",
        "Pivotally, placably, placidly, plainly and plaintively, they lived planetary, plastically, platitudinously, platonically, and plausibly.",
        "Playfully, pleadingly, pleasantly, pleasingly and pleasurably, they lived plenarily, plenteously, plentifully, pliably, and ploddingly.",
        "Plumply, poetically, poignantly, pointedly and pointlessly, they lived poisedly, poisonously, polarizedly, politically, and polishedly.",
        "Politely, politicly, pollistically, polyphonically and pompously, they lived ponderously, poorly, popularly, populationally, and porously.",
        "Portably, portentously, posedly, positively and possessively, they lived possibly, post-haste, posthumously, postoperatively, and potentially.",
        "Potently, powerfully, powerlessly, practicably and practically, they lived pragmatically, praiseworthily, precariously, precedentially, and preceptively.",
        "Preciously, precipitately, precipitously, precisely and precociously, they lived precursively, predatorily, predeterminately, predicatively, and predictably.",
        "Predominantly, pre-eminently, pre-emptively, preferentially and preferringly, they lived pregnantly, prehistorically, prejudicially, prematurely, and premeditatedly.",
        "Premierly, premonitorily, preoccupiedly, preparatorily and preposterously, they lived prerecordedly, presciently, prescriptively, presently, and presidentially.",
        "Pressingly, prestigiously, presumably, presumptuously and pretendingly, they lived pretentiously, preternaturally, prettily, pretty, and prevailingly.",
        "Prevalent, preventatively, previously, primally and primarily, they lived primly, princely, principally, principledly, and printably.",
        "Prior, priorly, privately, privatively and privilegedly, they lived prizedly, proactively, probabilistically, probably, and probatively.",
        "Problematically, procedurally, processionally, proclaimedly and procrastinatingly, they lived procreatively, proctorially, procurably, prodigally, and prodigiously.",
        "Productively, profanely, professedly, professionally and professorially, they lived proficiently, profitably, profligately, profoundly, and profusely.",
        "Prognostically, programmatically, progressively, prohibitively and projectively, they lived prolificly, prolixly, prolongedly, prominently, and promiscuously.",
        "Promisingly, promptly, pronouncedly, proofly and propagandistically, they lived properly, prophetically, propitiously, proportionally, and proportionately.",
        "Propositionally, proprietarily, propriously, prosaically and proscriptively, they lived prosperously, protectively, protractedly, proudly, and provably.",
        "Proverbially, providently, providially, provincially and provisionally, they lived provocatively, provokingly, prudently, prudishly, and pryingly.",
        "Psalmically, pseudonymously, psychically, psychologically and psychopathically, they lived publicly, puffily, pugnaciously, puissantly, and punctiliously.",
        "Punctually, pungently, punily, punishingly and punitively, they lived purely, puritanically, purportedly, purposefully, and purposely.",
        "Purposively, pursuants, pushingly, pusillanimously and putatively, they lived pyramidically, quackishly, quaintly, quakingly, and qualifiedly.",
        "Qualitatively, quantitatively, quarrelsomely, quarterly and quaveringly, they lived queasily, queerly, quenchlessly, querulously, and questionably.",
        "Questioningly, quick, quickly, quiescently and quietly, they lived quintessentially, quiveringly, quixotically, quizzically, and quotably.",
        "Racially, racily, radically, radioactively and radiographically, they lived raggedly, railingly, rainily, rakishly, and rallyingly.",
        "Ramblingly, rampantly, rancorously, randomly and rapidly, they lived rapturously, rarely, raspy, ratably, and rather.",
        "Ratifyingly, rationally, raucously, ravenously and ravishingly, they lived readily, real, realistically, really, and rear.",
        "Rearward, rearwards, reasonably, reassuringly and rebellionly, they lived rebukingly, recalcitrantly, recently, receptively, and reciprocally.",
        "Recklessly, reclusively, recognizably, recollectedly and recombinantly, they lived recommendably, recompensingly, reconcilingly, reconditely, and reconstructively.",
        "Recordedly, recountingly, recoverably, recreationally and rectangularly, they lived rectilinearly, recumbently, recurrently, recursively, and redly.",
        "Redolently, redoubtably, reductively, redundantly and reefward, they lived reekingl, reflectively, reflexively, reformatively, and refractively.",
        "Refreshingly, refulgent, regally, regardlessly and regimentally, they lived regionally, regretfully, regrettably, regularly, and regurgitatingly.",
        "Rehabilitatively, rehearsedly, reigningly, reiteratedly and rejectingly, they lived rejoicingly, relatedly, relatively, relentlessly, and relevant.",
        "Relevantly, reliably, reliefly, relievedly and religionly, they lived religiously, reluctantly, remarkables, remarkably, and remedially.",
        "Reminiscently, remissly, remorselessly, remotely and removably, they lived renownedly, repeatedly, repellingly, repentants, and repetitiously.",
        "Repetitively, reportedly, reposefully, reprehensibly and representatively, they lived repressively, reproachfully, reproducibly, reproofly, and reproveably.",
        "Repulsively, reputedly, requestingly, requiringly and requitingly, they lived resentfully, reservedly, resignedly, resiliently, and resistantly.",
        "Resistlessly, resolutely, resonantly, resortingly and resourcefully, they lived respectably, respectfully, respectively, resplendently, and responsibly.",
        "Responsively, restfully, restively, restlessly and restrestrictively, they lived resultantly, retailly, retaliatorily, retentively, and reticently.",
        "Retiringly, retrospectively, revengefully, reverently and reverentially, they lived reversely, reversibly, revertibly, revilingly, and revoltingly.",
        "Revolutionarily, rewardingly, rhythmically, richly and ridiculously, they lived right, righteously, rightfully, rightly, and rigidly.",
        "Rigorously, riotously, ripely, riskily and ritually, they lived rivetingly, roaringly, robotically, robustly, and rockily.",
        "Roguishly, rolandically, rollingly, romantically and rompishly, they lived roomily, rooteddy, rosily, rotarily, and rotundly.",
        "Roughly, round, roundly, routinely and rowdily, they lived royally, rudely, rudimentarily, ruefully, and ruggedly.",
        "Ruinously, ruminatively, rumoredly, rumplingly and runically, they lived runnily, rushedly, rushingly, rustically, and rustily.",
        "Ruthlessly, sacramental, sacredly, sacrificially and sacrilegiously, they lived sadly, safe, safely, sagely, and salaciously.",
        "Saliently, saline, saltily, salubriously and salutarily, they lived salvageably, same, sanctuarily, sanely, and sanguinely.",
        "Sanitarily, sapiently, sarcastically, sardonically and saucily, they lived satiably, satirically, satisfactorily, satisfyingly, and saturately.",
        "Sauvily, savagely, savilly, savvy and scabrously, they lived scandalously, scantily, scantly, scarcely, and scaringly.",
        "Scarily, scathingly, scatteredly, scenically and scentedly, they lived skeptically, schedulingly, schematically, scholastically, and scholarly.",
        "Scientifically, scintillatingly, scornfully, scotch and scoundrelly, they lived scowlingly, scraggily, scrappily, scratchily, and scrawnily.",
        "Screamingly, screechingly, scripturally, scrupulously and scrutinizingly, they lived scurrilously, sculpturally, seamlessly, searchingly, and seasickly.",
        "Seasonably, seasonally, seaward, seawards and secludedly, they lived secondarily, secondhandedly, secondly, secretarial, and secretively.",
        "Secretly, sectarianly, secularly, securely and sedately, they lived sedimentarily, seductively, sedulously, seemingly, and seemly.",
        "Seismically, seldom, selectively, self-consciously and self-evidently, they lived selfishly, selflessly, semantically, seminally, and semi-professionally.",
        "Sensationally, senselessly, sensibly, sensitively and sensitorily, they lived sensually, sensuously, sententially, sentiently, and sentimentally.",
        "Separately, separatively, septically, sequentially and serenely, they lived serially, seriously, sermonically, servilely, and settledly.",
        "Severely, sexually, shabbily, shadily and shadowily, they lived shaggily, shakily, shallowly, shamelessly, and shapelessly.",
        "Shapely, sharply, shatteringly, sheepishly and sheerly, they lived shiftily, shimmeringly, shinily, shiveringly, and shockingly.",
        "Shoddily, shoeless, shortly, short-sightedly and shrewdly, they lived shrilly, shrinkingly, shudderingly, shufflingly, and shunnably.",
        "Shyly, sickeningly, sickly, sideways and sidelong, they lived sideward, sidewards, sighingly, sightlessly, and signally.",
        "Significantly, silently, silkily, silly and silvically, they lived similarly, simperingly, simple, simpatico, and simplistically.",
        "Simply, sincerely, sine, sinewily and sinfully, they lived sinuously, sirenically, skeptically, sketchily, and skillfully.",
        "Skimpily, skittishly, skyward, skywards and slackly, they lived slanderously, slantingly, slantwise, slashingly, and slavishly.",
        "Sleekly, sleepily, sleeplessly, slenderly and slickly, they lived slightly, slimly, slingingly, slinkily, and slippily.",
        "Slippery, slitly, sloppily, sloshingly and slowly, they lived sluggishly, slumberously, slyly, small, and smarmily.",
        "Smartly, smashingly, smellingly, smilingly and smirkingly, they lived smokily, smoothly, smotheringly, smugly, and smutty.",
        "Snappily, sneakingly, sneeringly, snidely and sniffingly, they lived snobbishly, snoozingly, snowily, snugly, and so.",
        "Soakly, soapily, soaringly, sobbingly and soberly, they lived sociably, socially, socioeconomically, sociologically, and soft.",
        "Softly, soggy, solely, solemnly and solicitously, they lived solidly, solitarily, solo, solubly, and somberly.",
        "Some, somehow, someway, someways and somewhere, they lived somnambularly, somnolently, sonically, sonrously, and soon.",
        "Soothingly, sophistically, sophisticatedly, sordidly and sorely, they lived sorrowfully, sorry, sortablely, sottingly, and sotto voce.",
        "Sought, soulfully, soundlessly, soundly and sourly, they lived south, southward, southwards, sovereignly, and spaceably.",
        "Spaciously, spanlessly, sparingly, sparkingly and sparsely, they lived spasmodically, spatially, specially, specifically, and speciously.",
        "Spectacularly, spectrally, speculatively, speechlessly and speedily, they lived spellbindingly, spendthriftly, spherically, spicily, and spidery.",
        "Spinelessly, spirally, spiritedly, spiritually and spitefully, they lived splendidly, splenetically, spokenly, spongily, and spontaneously.",
        "Spookily, sporadically, sportily, spotlessly and sprawlly, they lived spreadingly, sprightly, springily, spunkily, and spuriously.",
        "Squalidly, squally, squanderly, squarely and squeakily, they lived squeamishly, squeezingly, squintingly, stably, and staccato.",
        "Staggeringly, stagnantly, staidly, stainlessly and stale, they lived stalwartly, stammeringly, standardly, standingly, and staringly.",
        "Starkly, starry, startlingly, statesmanly and statistically, they lived statuesquely, statutorily, steadfastly, steadily, and stealthily.",
        "Steamily, steely, steeply, stellar and stepwise, they lived stereotypically, sterilely, sternly, stickingly, and stiffly.",
        "Stiflingly, stigma-free, still, stiltedly and stimulatingly, they lived stingily, stinkingly, stirringly, stockily, and stolidly.",
        "Stonily, stoically, stoopingly, stormily and stoutly, they lived straight, straightforwardly, straitly, strangely, and strategically.",
        "Strenuously, stressfully, stretchily, strikingly and stringently, they lived stroboscopically, strongly, structurally, stubbornly, and studiously.",
        "Stultifyingly, stumblingly, stunnedly, stunningly and stupefyingly, they lived stupendously, stupidly, sturdily, stutteringly, and stylishly.",
        "Stylistically, suavely, subconsciously, subcutaneously and subduedly, they lived subjectively, sublimely, subliminally, submissively, and subordinately.",
        "Subsequent, subsequently, subserviently, subsidially and substantially, they lived substantively, subtly, subtractively, suburbly, and subversively.",
        "Successively, succinctly, succulently, such and suddenly, they lived sufferably, sufficiently, suffocatingly, suggestively, and suitably.",
        "Sulkily, sullenly, s sultrily, summarily and summerly, they lived sumptuously, sunnily, superabundantly, superbly, and superciliously.",
        "Superficially, superfluously, superhumanly, superlatively and supernaturally, they lived supersonically, superstitiously, supinely, supposedly, and suppressively.",
        "Supremely, sure, surely, surgically and surlily, they lived surmountably, surpassingly, surprisedly, surprisingly, and surrealistically.",
        "Surreptitiously, suspectly, suspiciously, sustainably and sustainedly, they lived swaggeringly, swankily, swarthy, sweatingly, and sweepingly.",
        "Sweetly, swelteringly, swiftly, swimmingly and swirlingly, they lived syllabically, syllogistically, symbolically, symmetrically, and sympathetically.",
        "Symptomatically synchronously, the syncopatedly syndic synergistically acts synonymously with the synoptic syntactically synthetic system.",
        "Tabooly dressed, they acted tacitly and taciturnly, though tackily and tactfully tactically maneuvered, though tactlessly and tailorly talentedly and talismanically.",
        "Talkatively and tamely, they moved tangentially and tangibly, tannically and tantalizingly, though tardily and tartly, tastefully and tastelessly.",
        "Tastily and tatteredly, they moved tauntingly and tautly, tautologically and tavernly, tawdrily and taxably, taxonomically and tearfully.",
        "Teasingly and technically, technologically and tediously, they were teemingly, telegraphically, telepathically, telescopically, temerariously, and temperamentally.",
        "Temperately and tempestuously, temporally and temporarily, they acted temptingly, tenably, tenaciously, tendentiously, tenderly, and tenebrously.",
        "Tensely and tensilely, tentatively and tenuously, they lived tepidly, terminally, terminologically, terrestrially, terribly, and terrifically.",
        "Territorially and tersely, testily and tetheredly, they acted thankfully, theatrically, theistically, themely, then, and thence.",
        "Theologically and theoretically, therapeutically, they lived there, thereabouts, thereafter, thereby, therefore, therein, and thereof.",
        "Thereon and thereto, thereunder and thereupon, they lived therewith, thermally, thermodynamically, thickly, thiefly, and thinly.",
        "Thirstily and thither, thornily and thoroughly, they lived thoughtfully, thoughtlessly, threateningly, thrifty, thrillingly, and throbbingly.",
        "Through and throughout, thumpingly and thunderingly, they acted thus, thwartedly, tidily, tight, tightly, and timely.",
        "Timidly and tinderly, tinklingly, tinny and tintedly, they lived tirade-ly, tirelessly, tiresomely, titanically, and titularly.",
        "To and today, together, tolerably and tolerantly, they lived tonally, tonight, too, topically, and topographically.",
        "Toppingly and torpidly, torrentially, torridly and tortuously, they lived torturously, totally, touchily, touchingly, and toughly.",
        "Toward and towards, toxically, traceably and traditionally, they lived tragically, traitorously, tranquilly, transactly, and transcendentally.",
        "Transcriptionally and transfusedly, transiently, transitionally and translationally, they lived translucently, transparently, transpirationally, transversely, and treacherously.",
        "Treasonably and treasuredly, tremendously, tremulously and trenchantly, they lived trepidly, triannually, tribally, trickily, and tricoloredly.",
        "Triflingly and trillingly, trimly, trinitarianly and tripitaka-ly, they lived triple, tritely, triumphally, triumphantly, and trivially.",
        "Troglodytically and tropically, trottingly, troublesomely and troublingly, they lived truantly, truculently, true, truly, and truncatedly.",
        "Trustfully and trustingly, trustworthily, truthfully and tumidly, they lived tumultuously, tunefully, tunelessly, turbidly, and turbulently.",
        "Turgidly and turkey, turpitudinously, twinly and twinklingly, they lived twitchily, two-dimensionally, two-facedly, two-fold, and typically.",
        "Typographically and tyrannically, ubiquitously, uglily and ulteriorly, they lived ultimately, ultramodernly, umbrageously, unabashedly, and unacceptably.",
        "Unaccountably and unaccustomedly, unadulteratedly, unadvisedly and unaffectedly, they lived unalterably, unambiguously, unambitiously, unamiably, and unanimously.",
        "Unanswerably and unapologetically, unappeasably, unappreciatively and unapproachably, they lived unarmedly, unashamedly, unassailably, unassumingly, and unattachedly.",
        "Unattainably and unattractively, unauspiciously, unauthentically and unavailingly, they lived unavoidably, unawares, unbearably, unbecomingly, and unbelievably.",
        "Unbendingly and unbiasedly, unblinkingly, unblushingly and unboundedly, they lived unbrokenly, uncannily, unceasingly, unceremoniously, and uncertainly.",
        "Uncharitably and unchivalrously, uncivilly, uncleanly and unclearly, they lived uncomfortably, uncommon, uncommonly, uncompromisingly, and unconcernedly.",
        "Unconditionally and unconsciously, unconstitutionally, uncontrollably and unconventionally, they lived unconvincingly, uncooly, uncooperatively, uncoordinatedly, and uncountably.",
        "Uncritically and unctuously, undauntedly, undecidedly and undemonstratively, they lived undeniably, under, underarm, underfoot, and underhand.",
        "Underhandedly and underlyingly, underneath, understandably and understandingly, they lived understatedly, undeservedly, undesirably, undeviatingly, and undignifiedly.",
        "Undisguisedly and undisputedly, undisturbedly, undividedly and undogmatically, they lived undramatically, unduly, undyingly, unearthly, and uneasily.",
        "Unedifyingly and unemotionally, unendingly, unendurably and unenergetically, they lived unenviably, unequally, unequivocally, unerringly, and unethically.",
        "Unevenly and uneventfully, unexceptionally, unexcitedly and unexcusably, they lived unexhaustedly, unexpectedly, unexpensively, unexpertly, and unexplainably.",
        "Unexplicitly and unexploringly, unexpressively, unfailingly and unfairly, they lived unfaithfully, unfalteringly, unfamiliarly, unfashionably, and unfavorably.",
        "Unfeelingly and unfeignedly, unfilially, unflinchingly and unforcefully, they lived unforeseeably, unforgettably, unforgivably, unfortunately, and unfoundedly.",
        "Unfriendly and unfruitfully, ungainly, ungallantly and ungenerously, they lived ungenteelly, ungently, ungrudgingly, unguardedly, and unguiltily.",
        "Unhappily and unharmoniously, unhealthily, unhesitatingly and unhelpfully, they lived unholily, unhurriedly, unidirectionally, uniformly, and unimaginably.",
        "Unimaginatively and unimpeachably, unimpededly, unimportantly and unimpressively, they lived uninformatively, uninstructively, unintelligently, unintelligibly, and unintentionally.",
        "Uninterestedly and uninterruptedly, unintimidatedly, unintoxicatingly and unintrusively, they lived unintuitively, uninventively, uninvitingly, uninvolvedly, and unironically.",
        "Unjustifiably and unjustly, unkindly, unknowingly and unknowledgeably, they lived unladylike, unlawfully, unlearnedly, unleavenedly, and unless.",
        "Unlickedly and unlikely, unlimitedly, unlinearly and unlinguistically, they lived unliterarily, unlocally, unlogically, unlovingly, and unluckily.",
        "Unmanly and unmannerly, unmanufacturedly, unmarkedly and unmarriedly, they lived unmaskingly, unmasterably, unmeaningly, unmeasuredly, and unmechanically.",
        "Unmelodiously and unmemorably, unmendably, unmentionably and unmercifully, they lived unmeritedly, unmethodically, unmindfully, unmistakably, and unmitigatedly.",
        "Unmixedly and unmodishly, unmolestedly, unmonumentally and unmovably, they lived unmurmuringly, unmusically, unmuzzlely, unmysteriously, and unnaturally.",
        "Unnecessarily and unneighborly, unnervingly, unnoticeably and unobjectionably, they lived unobligingly, unobnoxiously, unobscurely, unobservantly, and unobstructedly.",
        "Unobtrusively and unobviously, unoccupiedly, unoffensively and unofficially, they lived unopenly, unopposedly, unoppressively, unorganizedly, and unoriginally.",
        "Unorthodoxly and unostentatiously, unpackedly, unpalatably and unpardonably, they lived unpatriotically, unpeaceably, unperceivably, unperfectly, and unphilosophically.",
        "Unphysically and unpityingly, unpleasantly, unpleasingly and unpoetically, they lived unpolishedly, unpolitely, unpolitically, unpopularly, and unprecedentedly.",
        "Unpredictably and unprejudicedly, unpremeditatedly, unpreparedly and unprepossessingly, they lived unpretendingly, unpretentiously, unprincipledly, unprintably, and unproductively.",
        "Unprofessionally and unprofitably, unpromisingly, unpromptedly and unpronouncedly, they lived unpropitiously, unprotectively, unprovokedly, unprudently, and unpunishedly.",
        "Unquestionably and unquestioningly, unquietly, unreadably and unreadily, they lived unrealistically, unreally, unreasonably, unreasoningly, and unreceptively.",
        "Unrecognizably and unrecordedly, unreflectingly, unregenerately and unrelatedly, they lived unrelentingly, unreliably, unrelievedly, unremarkably, and unremittingly.",
        "Unremorsefully and unrepentantly, unreservedly, unresistingly and unresponsively, they lived unrestrainedly, unrestrictedly, unrevealedly, unrevengingly, and unrewardingly.",
        "Unrighteously and unrightfully, unripely, unrivaledly and unromantically, they lived unruffledly, unrulily, unsafely, unsaid, and unsanitarily.",
        "Unsatisfactorily and unsatisfyingly, unsavoryly, unsayably and unscrupulously, they lived unseasonably, unseasonedly, unseaworthily, unsecondedly, and unsecretively.",
        "Unsectarianly and unsecularly, unsecurely, unsedately and unseemingly, they lived unseemly, unsegregatedly, unselectively, unselfconsciously, and unselfishly.",
        "Unselfishly and unsensational, unsensibly, unsensitively and unsensuously, they lived unsententially, unsentiently, unsentimentally, unseparably, and unseparatively.",
        "Unserviceably and unsettledly, unseverely, unshakably and unshakily, they lived unshamedly, unshapely, unsharply, unshatterably, and unsheathedly.",
        "Unshrivenly and unshrinkingly, unshutly, unsightedly and unsignificantly, they lived unsilently, unsimilarly, unsimply, unsincerely, and unsinfully.",
        "Unsinkably and unsinuously, unsisterly, unskillfully and unskimpingly, they lived unslakedly, unsleepingly, unslowly, unsmilingly, and unsmirkingly.",
        "Unsmutty and unsnappily, unsneakingly, unsnidely and unsnobbishly, they lived unsnowily, unsnugly, unsoakly, unsoberly, and unsociably.",
        "Unsocially and unsoftly, unsolemnly, unsolicitously and unsolidly, they lived unsolubly, unsomberly, unsonically, unsoothingly, and unsophisticatedly.",
        "Unsoundly and unsourly, unsparingly, unspeakably and unspecifically, they lived unspectacularly, unspeculatively, unspiritually, unspitefully, and unsplendidly.",
        "Unspokenly and unsportily, unspotlessly, unstably and unstanchably, they lived unstately, unstatutorily, unsteadfastly, unsteadily, and unstealthily.",
        "Unstintingly and unstirringly, unstoically, unstoppingly and unstrainedly, they lived unstrategically, unstrenuously, unstressfully, unstrikingly, and unstructurally.",
        "Unstudiously and unstultifyingly, unstunningly, unsuavely and unsubduedly, they lived unsubstantially, unsubtly, unsuccessfully, unsuccinctly, and unsufferably.",
        "Unsufficiently and unsuitably, unsullenly, unsumptuously and unsunnily, they lived unsuperfluously, unsuperstitiously, unsurely, unsurpassably, and unsurprisingly.",
        "Unsuspectingly and unsustainably, unswervingly, unswervingly and unsympathetically, they lived unsystematically, untactfully, untalentedly, untamedly, and untangibly.",
        "Untardily and untastefully, untastily, untaughtly and untechnically, they lived untediously, untemperately, untenably, untenantedly, and untenderly.",
        "Untensely and untentatively, unterminally, unterrestrially and unterribly, they lived unthankfully, untheatrically, untheoretically, unthinkably, and unthinkingly.",
        "Unthoroughly and unthoughtfully, unthoughtlessly, unthreateningly and unthriftily, they lived unthrillingly, untidily, untightenly, untimely, and untimidly.",
        "Untiringly and untolerably, untolerantly, untonally and untopical, they lived untorpidly, untouchably, untraceably, untraditionally, and untragically.",
        "Untranquilly and untransparently, untreacherously, untremulously and untrenchantly, they lived untriflingly, untrimly, untritely, untriumphantly, and untrivially.",
        "Untroublesomely and untroublingly, untrue, untruly and untrustfully, they lived untrustingly, untrustworthily, untruthfully, untumultuously, and untunefully.",
        "Unturbulently and untypically, unubiquitously, unusually and unutterably, they lived unvacillatingly, unvaluably, unvariably, unvaryingly, and unveiledly.",
        "Unvenerably and unverbally, unverifiably, unversed-ly and unvexedly, they lived unvibrantly, unviciously, unvictoriousy, unvigilantly, and unvigorously.",
        "Unvirtuously and unvisibly, unvitally, unvividly and unvocally, they lived unvoluminously, unvoluntarily, unvulnerably, unwarily, and unwarmly.",
        "Unwarrantably and unwarrantedly, unwaryly, unwaveringly and unweariedly, they lived unwearyingly, unweekly, unweighedly, unwelcome, and unwell.",
        "Unwholesomely and unwickedly, unwidely, unwildly and unwillingly, they lived unwindingly, unwisely, unwittingly, unwontedly, and unworkably.",
        "Unworldly and unworthily, unworthily, unyieldingly and up, they lived upbeatly, upward, upwards, urbanely, and urgently.",
        "Usably and usefully, uselessly, usually and usuriously, they lived utmostly, utterly, vacantly, vacillatingly, and vacuously.",
        "Vaguely and vainly, valiantly, validly and valorously, they lived valuably, vanishingly, vapidly, vaporously, and variably.",
        "Variedly and variously, vastly, vauntingly and vehemently, they lived vehicularly, velociously, venally, venerably, and vengefully.",
        "Venially and venomously, ventrally, venturesomely and veraciously, they lived verbally, verbatim, verbosely, verdantly, and verifiably.",
        "Verily and veritably, vernacularly, versatilely and vertically, they lived very, vespertinely, vexatiously, vexedly, and viably.",
        "Vibrantly and vicariously, vice versa, viciously and victoriously, they lived viewably, vigilantly, vigorously, vilely, and villainously.",
        "Vindictively and violably, violently, virginly and virilely, they lived virtually, virtuously, virulently, viscerally, and visibly.",
        "Visionarily and visually, vitally, vitriolically and vivaciously, they lived vividly, vocally, vocationally, vociferously, and voicelessly.",
        "Voidly and volatily, volcanically, volitionally and volubly, they lived voluminously, voluntarily, voluptuously, voraciously, and votively.",
        "Vulgarly and vulnerably, waggishly, wailingly and waitingly, they lived wakefully, wanly, wantonly, warily, and warmly.",
        "Warningly and warrantably, warrantedly, warringly and warily, they lived washably, wastefully, watchfully, waterily, and waveringly.",
        "Waywardly and weakly, wealthily, wearily and wearyingly, they lived weekly, weepingly, weighingly, weightily, and weirdly.",
        "Welcome and well, westerly, westward and westwards, they lived wetly, whimsically, whiningly, whippingly, and whirlingly.",
        "Whiskingly and whisperingly, whistlingly, white and wholly, they lived whoppingly, wickedly, wide, widely, and wildly.",
        "Wilfully and willingly, willowily, wily and wincedly, they lived windily, wingedly, winkingly, winningly, and winlessly.",
        "Winsomely and winterly, wintery, wisely and wishfully, they lived wispily, wistfully, witchingly, witheringly, and within.",
        "Without and witlessly, wittingly, wittily and wizardly, they lived woefully, wolfishly, womanly, wonderingly, and wonderfully.",
        "Wondrously and woodily, wooingly, wordily and wordlessly, they lived workably, worldly, world-wearily, worriedly, and worryingly.",
        "Worse and worshipfully, worst, worthily and worthlessly, they lived woundedly, wrathfully, wreakly, wretchedly, and writhingly.",
        "Wrong and wrongfully, wrongly, wroughtly and wryly, they lived xenophobically, xerographically, xerically, yawningly, and yearly.",
        "Yearningly and yellowly, yelpingly, yes and yesterday, they lived yieldingly, yokingly, yonder, youthfully, and zealously.",
        "Zestfully and zestily, zigzag, zinc-ly and zionistically, they lived zodiacally, zonally, zoologically, zoomingly, and zymotically."
    ];

    try {
        // 1. Fetch current Level 7 content
        const { data: existingContent, error: fetchError } = await supabase
            .from('level_content')
            .select('*')
            .eq('level_id', targetLevelId)
            .order('order_index', { ascending: true });

        if (fetchError || !existingContent) {
            throw new Error(`Failed to fetch Level 7 content: ${fetchError?.message}`);
        }

        // 2. Locate the starting index based on the specific words provided
        const startTarget = "Abnormally, Aboard, About, Above, Abroad";
        const startIndex = existingContent.findIndex(item => item.item_a === startTarget);

        if (startIndex === -1) {
            throw new Error(`Target item_a text "${startTarget}" not found in Level 7 content.`);
        }

        console.log(`📍 Found start point at index ${startIndex}. Preparing updates for ${paragraphs.length} items.`);

        // 3. Prepare updates
        for (let i = 0; i < paragraphs.length; i++) {
            const currentItem = existingContent[startIndex + i];

            if (!currentItem) {
                console.warn(`⚠️ Narrative paragraph ${i} has no matching row in level_content at index ${startIndex + i}. Stopping.`);
                break;
            }

            const { error: updateError } = await supabase
                .from('level_content')
                .update({ item_b: paragraphs[i] })
                .eq('id', currentItem.id);

            if (updateError) {
                console.error(`❌ Error updating row ${currentItem.id} (item_a: ${currentItem.item_a}):`, updateError.message);
            }
        }

        console.log('✨ Level 7 Narrative update finished successfully!');

    } catch (err) {
        console.error('💀 Seeding failed:', err);
    }
}

seedLevel7Narrative();